### ISSUE TITLE
Getting error when starting juggernaut server

### ISSUE THREAD

**Issue by VinothiniBalakrishnan** [maccman/juggernaut#107]
First I started redis server by

spritle@ubuntu:~/Desktop/spine.realtime$ sudo /etc/init.d/redis-server start
Starting redis-server: redis-server.

Next step try to start juggernaut server as

spritle@ubuntu:/usr/local/lib/node_modules/juggernaut$ juggernaut 
   info  - socket.io started
node_redis: no callback to send error: ERR unknown command 'subscribe'

node.js:205
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: ERR unknown command 'subscribe'
    at RedisReplyParser.<anonymous> (/usr/local/lib/node_modules/juggernaut/node_modules/redis/index.js:78:27)
    at RedisReplyParser.emit (events.js:67:17)
    at RedisReplyParser.send_error (/usr/local/lib/node_modules/juggernaut/node_modules/redis/lib/parser/javascript.js:265:14)
    at RedisReplyParser.execute (/usr/local/lib/node_modules/juggernaut/node_modules/redis/lib/parser/javascript.js:124:22)
    at RedisClient.on_data (/usr/local/lib/node_modules/juggernaut/node_modules/redis/index.js:358:27)
    at Socket.<anonymous> (/usr/local/lib/node_modules/juggernaut/node_modules/redis/index.js:93:14)
    at Socket.emit (events.js:67:17)
    at Socket._onReadable (net_legacy.js:684:14)
    at IOWatcher.onReadable [as callback](net_legacy.js:177:10)

**Comment by maccman** [comment]
You need to upgrade Redis.
