### ISSUE TITLE
Juggernaut error

### ISSUE THREAD

**Issue by VinothiniBalakrishnan** [maccman/juggernaut#108]
I updated the redis

When i running redis 

spritle@ubuntu:~/redis-2.4.4/src$ redis-server
15 Dec 12:32:42 \* Warning: no config file specified, using the default config. In order to specify a config file use 'redis-server /path/to/redis.conf'
15 Dec 12:32:42 - Server started, Redis version 1.2.0
15 Dec 12:32:42 \* WARNING overcommit_memory is set to 0! Background save may fail under low condition memory. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
15 Dec 12:32:42 - The server is now ready to accept connections on port 6379
15 Dec 12:32:42 . 0 clients connected (0 slaves), 412114 bytes in use, 0 shared objects
....
...
....
....

After that i try to start juggernaut
I am getting the same error
spritle@ubuntu:~/Desktop/vino-tryouts/juggernaut$ juggernaut 
   info  - socket.io started
node_redis: no callback to send error: ERR unknown command 'subscribe'

node.js:205
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: ERR unknown command 'subscribe'
    at RedisReplyParser.<anonymous> (/usr/local/lib/node_modules/juggernaut/node_modules/redis/index.js:78:27)
    at RedisReplyParser.emit (events.js:67:17)
    at RedisReplyParser.send_error (/usr/local/lib/node_modules/juggernaut/node_modules/redis/lib/parser/javascript.js:265:14)
    at RedisReplyParser.execute (/usr/local/lib/node_modules/juggernaut/node_modules/redis/lib/parser/javascript.js:124:22)
    at RedisClient.on_data (/usr/local/lib/node_modules/juggernaut/node_modules/redis/index.js:358:27)
    at Socket.<anonymous> (/usr/local/lib/node_modules/juggernaut/node_modules/redis/index.js:93:14)
    at Socket.emit (events.js:67:17)
    at Socket._onReadable (net_legacy.js:684:14)
    at IOWatcher.onReadable [as callback](net_legacy.js:177:10)

**Comment by mbyczkowski** [comment]
You said that you have upgraded your redis server, but the output says you are running Redis 1.2.0.

Juggernaut uses Redis for communicating using SUBSCRIBE command, which is available since Redis 1.3.8. Make sure that you are using your new version of Redis.

**Comment by maccman** [comment]
Upgrade to Redis 3.3.12.

**Comment by mbyczkowski** [comment]
@maccman I thought the latest stable Redis was 2.4.4?

**Comment by maccman** [comment]
Yes, sorry, that's the one I mean - that'll work. Anything newer than 1.2.0 ;)

**Comment by VinothiniBalakrishnan** [comment]
I downloaded redis from http://redis.io/download. After extraction of redis-2.4.4.tar.gz I am getting redis-2.4.4. After that I did the following 
spritle@ubuntu:~$ cd Desktop/redis-2.4.4/
spritle@ubuntu:~/Desktop/redis-2.4.4$ make
cd src && make all
make[1]: Entering directory `/home/spritle/Desktop/redis-2.4.4/src'
MAKE hiredis
.....
....
....

Then next step
spritle@ubuntu:~/Desktop/redis-2.4.4$ cd src
spritle@ubuntu:~/Desktop/redis-2.4.4/src$ redis-server 

Still i m getting the 
16 Dec 11:29:27 \* Warning: no config file specified, using the default config. In order to specify a config file use 'redis-server /path/to/redis.conf'
16 Dec 11:29:27 - Server started, Redis version 1.2.0
16 Dec 11:29:27 \* WARNING overcommit_memory is set to 0! Background save may fail under low condition memory. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
16 Dec 11:29:27 - The server is now ready to accept connections on port 6379
16 Dec 11:29:27 . 0 clients connected (0 slaves), 412114 bytes in use, 0 shared objects

May i did anything wrong

**Comment by VinothiniBalakrishnan** [comment]
Hi I followed https://redistogo.com/documentation/introduction_to_redis. Download redis-2.0.0 and start the redis server 
spritle@ubuntu:~/redis-2.0.0-rc1$ redis-server
[5312] 16 Dec 11:44:18 # Warning: no config file specified, using the default config. In order to specify a config file use 'redis-server /path/to/redis.conf'
[5312] 16 Dec 11:44:18 \* Server started, Redis version 1.3.14
[5312] 16 Dec 11:44:18 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
[5312] 16 Dec 11:44:18 \* The server is now ready to accept connections on port 6379
[5312] 16 Dec 11:44:18 - 0 clients connected (0 slaves), 533436 bytes in use
[5312] 16 Dec 11:44:23 - 0 clients connected (0 slaves), 533436 bytes in use
[5312] 16 Dec 11:44:28 - 0 clients connected (0 slaves), 533436 bytes in use

And start the juggernaut 
spritle@ubuntu:/usr/local/lib/node_modules/juggernaut$ juggernaut server.js 
The "sys" module is now called "util". It should have a similar interface.
   info  - socket.io started
   debug - client authorized
   info  - handshake authorized 1132868371198808267
   debug - setting request GET /socket.io/1/xhr-polling/1132868371198808267?t=1324016234129
   debug - setting poll timeout
   debug - client authorized for 
   debug - clearing poll timeout
   debug - xhr-polling writing 1::
   debug - set close timeout for client 1132868371198808267
   debug - xhr-polling received data packet 3:::{"type":"subscribe","channel":"/observer"}

Now i can able to connect juggernaut server. 

Thank you so much for your guidelines.
