### ISSUE TITLE
TypeError: Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by maxcountryman** [maccman/juggernaut#115]
/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/transports/websocket/hybi-07-12.js:94
  if (this.req.headers.upgrade.toLowerCase() !== 'websocket') {
                               ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at WebSocket.onSocketConnect (/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/transports/websocket/hybi-07-12.js:94:32)
    at WebSocket.handleRequest (/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/transport.js:71:10)
    at WebSocket.Transport (/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/transport.js:31:8)
    at new WebSocket (/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/transports/websocket/hybi-07-12.js:60:13)
    at new WebSocket (/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/transports/websocket.js:31:17)
    at Manager.handleClient (/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/manager.js:626:19)
    at Manager.handleHTTPRequest (/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/manager.js:597:8)
    at Manager.handleRequest (/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/manager.js:559:12)
    at Server.<anonymous> (/usr/lib/node_modules/juggernaut/node_modules/socket.io/lib/manager.js:107:10)
    at Server.emit (events.js:67:17)

**Comment by maccman** [comment]
Can you try with master?

**Comment by maxcountryman** [comment]
Is it possible to pull from master with npm? (You'll have to excuse my lack of knowledge in regards to Node and such... :)

**Comment by maccman** [comment]
Pull master from github, then run: npm install -g .
