### ISSUE TITLE
Server crashes on unproperly formatted message

### ISSUE THREAD

**Issue by mrbrdo** [maccman/juggernaut#12]
If you send a message with unexpected strcture (e.g. a string) the server will crash. I believe it should be fixed since otherwise it cannot be safely used in production.

Example of error:

SyntaxError: Unexpected token ILLEGAL
    at Object.parse (native)
    at Function.fromJSON (/home/mrbrdo/rails/mystery_chat/juggernaut/lib/juggernaut/message.js:8:24)
    at [object Object].onmessage (/home/mrbrdo/rails/mystery_chat/juggernaut/lib/juggernaut/connection.js:19:27)
    at [object Object].<anonymous> (lib/superclass.js:42:19)
    at [object Object].emit (events:26:26)
    at [object Object]._onMessage (lib/socket.io/client.js:49:8)
    at [object Object]._handle (lib/socket.io/transports/websocket.js:100:8)
    at Stream.<anonymous> (lib/socket.io/transports/websocket.js:78:8)
    at Stream.emit (events:26:26)
    at IOWatcher.callback (net:484:33)

**Comment by maccman** [comment]
Thanks, fixed.
