### ISSUE TITLE
Juggernaut fails to start on Ubuntu

### ISSUE THREAD

**Issue by primary0** [maccman/juggernaut#124]
I am trying to start Juggernaut on Ubuntu 10.04 LTS. Given below is the error I am getting. Has anyone come across the problem before? Any feedback would be much appreciated. Thanks!

``` bash
root@SERVER:~/node# npm -v
1.1.12

root@SERVER:~/node# npm install juggernaut
npm http GET https://registry.npmjs.org/juggernaut
npm http 304 https://registry.npmjs.org/juggernaut
npm http GET https://registry.npmjs.org/node-static-maccman
npm http GET https://registry.npmjs.org/redis/0.6.6
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/socket.io/0.8.7
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/node-static-maccman
npm http 304 https://registry.npmjs.org/socket.io/0.8.7
npm http 304 https://registry.npmjs.org/redis/0.6.6
npm http GET https://registry.npmjs.org/redis/0.6.7
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/socket.io-client/0.8.7
npm http GET https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/policyfile/0.0.4
npm http 304 https://registry.npmjs.org/redis/0.6.7
npm http 304 https://registry.npmjs.org/socket.io-client/0.8.7
npm http 304 https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/uglify-js/1.0.6
npm http GET https://registry.npmjs.org/websocket-client/1.0.0
npm http GET https://registry.npmjs.org/xmlhttprequest/1.2.2
npm http 304 https://registry.npmjs.org/websocket-client/1.0.0
npm http 304 https://registry.npmjs.org/uglify-js/1.0.6
npm http 304 https://registry.npmjs.org/xmlhttprequest/1.2.2
juggernaut@2.1.1 ./node_modules/juggernaut 
├── node-static-maccman@0.5.3
├── redis@0.6.6
├── optimist@0.2.8 (wordwrap@0.0.2)
└── socket.io@0.8.7

root@SERVER:~/node# gem install juggernaut
Successfully installed juggernaut-2.1.1
1 gem installed
Installing ri documentation for juggernaut-2.1.1...
Installing RDoc documentation for juggernaut-2.1.1...

root@SERVER:~/node# juggernaut

node.js:244
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: The "sys" module is now called "util".
    at sys.js:1:69
    at NativeModule.compile (node.js:569:5)
    at Function.require (node.js:537:18)
    at Function._load (module.js:297:25)
    at Module.require (module.js:357:17)
    at require (module.js:373:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/juggernaut/node_modules/redis/lib/util.js:5:20)
    at Module._compile (module.js:444:26)
    at Object..js (module.js:462:10)
    at Module.load (module.js:351:32)


root@SERVER:~/node# redis-cli
redis 127.0.0.1:6379>
```

**Comment by maccman** [comment]
Yes, this is an issue with the latest node. I'm onto it.

**Comment by primary0** [comment]
I got around it by compiling node after downloading from the website, instead of cloning and compiling from the git repo. Thanks!
