### ISSUE TITLE
node static causing server to crash

### ISSUE THREAD

**Issue by ersatzryan** [maccman/juggernaut#125]
``` bash
ruby-1.9.2@afternoon[ryan-mbp:~/dev/afternoon] live-updates!
$ node -v
v0.6.13
ruby-1.9.2@afternoon[ryan-mbp:~/dev/afternoon] live-updates!
$ npm -v
1.1.12
ruby-1.9.2@afternoon[ryan-mbp:~/dev/afternoon] live-updates!
$ npm -g ls
/usr/local/lib
├─┬ juggernaut@2.1.1 
│ ├── node-static-maccman@0.5.4 
│ ├─┬ optimist@0.2.8 
│ │ └── wordwrap@0.0.2 
│ ├── redis@0.6.6 
│ └─┬ socket.io@0.8.7 
│   ├── policyfile@0.0.4 
│   ├── redis@0.6.7 
│   └─┬ socket.io-client@0.8.7 
│     ├── uglify-js@1.0.6 
│     ├── websocket-client@1.0.0 
│     └── xmlhttprequest@1.2.2 
└─┬ npm@1.1.12 
  ├── abbrev@1.0.3 
  ├── block-stream@0.0.5 
  ├── fstream@0.1.14 
  ├── graceful-fs@1.1.8 
  ├── inherits@1.0.0 
  ├── ini@1.0.2 
  ├── lru-cache@1.0.5 
  ├── minimatch@0.1.5 
  ├── mkdirp@0.3.0 
  ├─┬ node-gyp@0.3.7 
  │ ├── ansi@0.0.4 
  │ └─┬ glob@3.1.9 
  │   └── minimatch@0.2.2 
  ├── node-uuid@1.3.3 
  ├── nopt@1.0.10 
  ├── proto-list@1.0.0 
  ├── read@0.0.1 
  ├── request@2.9.153 
  ├── rimraf@2.0.1 
  ├── semver@1.0.13 
  ├── slide@1.1.3 
  ├── tar@0.1.13 
  └── which@1.0.5 
ruby-1.9.2@afternoon[ryan-mbp:~/dev/afternoon] live-updates!
$ juggernaut
The "sys" module is now called "util". It should have a similar interface.
   info  - socket.io started
> Error serving / - undefined

/usr/local/lib/node_modules/juggernaut/node_modules/node-static-maccman/lib/node-static.js:246
                util.error(err);
                     ^
TypeError: Object #<Object> has no method 'error'
    at [object Object].<anonymous> (/usr/local/lib/node_modules/juggernaut/node_modules/node-static-maccman/lib/node-static.js:246:22)
    at [object Object].emit (events.js:67:17)
    at Object.oncomplete (fs.js:1064:12)
ruby-1.9.2@afternoon[ryan-mbp:~/dev/afternoon] live-updates!
$ juggernaut
The "sys" module is now called "util". It should have a similar interface.
   info  - socket.io started
> Error serving /application.js - undefined

/usr/local/lib/node_modules/juggernaut/node_modules/node-static-maccman/lib/node-static.js:246
                util.error(err);
                     ^
TypeError: Object #<Object> has no method 'error'
    at [object Object].<anonymous> (/usr/local/lib/node_modules/juggernaut/node_modules/node-static-maccman/lib/node-static.js:246:22)
    at [object Object].emit (events.js:67:17)
    at Object.oncomplete (fs.js:1064:12)
```

Seems to start up just fine, however, when I access the server it throws the error above. This is all fresh install of node following instructions on the README

**Comment by maccman** [comment]
Yes, I'm in the middle of replacing node-static with express or strata. node-static has stopped working with the latest version of Node.

**Comment by nir0** [comment]
subscribing :)

**Comment by jpellerin** [comment]
Is there a recommended workaround?

**Comment by teejayvanslyke** [comment]
Confirmed here, too.

**Comment by kyamaguchi** [comment]
I got the same error and the output of `$ npm -g` was the same.
I have another environment that I created before and I got no error on that environment.
I took diff and the result was

```
 ├─┬ juggernaut@2.1.1 
-│ ├── node-static-maccman@0.5.3 
+│ ├── node-static-maccman@0.5.4 
 │ ├─┬ optimist@0.2.8 
 │ │ └── wordwrap@0.0.2 
 │ ├── redis@0.6.6 
```

I replaced node-static-maccman@0.5.4 in the failed environment with node-static-maccman@0.5.3 then it worked.

**Comment by oskarblom** [comment]
Any updates to this?

**Comment by maccman** [comment]
Yes, planning to move to Strata or Express - just haven't had the time yet. Would be awesome if someone could help with this.

**Comment by oskarblom** [comment]
I'll have a look.

**Comment by dortzur** [comment]
I've replaced node-static-maccman with [node-static](https://github.com/cloudhead/node-static) and that's what got it working
can someone validate this as well?

**Comment by alexandre-mbm** [comment]
See at [npmjs.com](https://www.npmjs.com/package/node-static-maccman): "**0.5.3** is the latest release".
