### ISSUE TITLE
getting list of opened sessions

### ISSUE THREAD

**Issue by nir0** [maccman/juggernaut#127]
documentation i found is very poor, and i cannot figure out how to get a list of opened connections, or users online
i've tried to search this info in redis, but it looks like empty...

**Comment by nir0** [comment]
roster code is outdated due to supermodel (Rails 3.2):

```
1.9.3p125 :001 > Roster
NoMethodError: undefined method `class_inheritable_array' for Roster:Class
    from /home/nir0/.rvm/gems/ruby-1.9.3-p125@tyu_development/bundler/gems/supermodel-d5c06b867111/lib/supermodel/base.rb:118:in `method_missing'
    from /home/nir0/.rvm/gems/ruby-1.9.3-p125@tyu_development/bundler/gems/supermodel-d5c06b867111/lib/supermodel/redis.rb:6:in `block in extended'
    from /home/nir0/.rvm/gems/ruby-1.9.3-p125@tyu_development/bundler/gems/supermodel-d5c06b867111/lib/supermodel/redis.rb:5:in `class_eval'
    from /home/nir0/.rvm/gems/ruby-1.9.3-p125@tyu_development/bundler/gems/supermodel-d5c06b867111/lib/supermodel/redis.rb:5:in `extended'
    from /home/nir0/.rvm/gems/ruby-1.9.3-p125@tyu_development/bundler/gems/supermodel-d5c06b867111/lib/supermodel/redis.rb:163:in `extend'
    from /home/nir0/.rvm/gems/ruby-1.9.3-p125@tyu_development/bundler/gems/supermodel-d5c06b867111/lib/supermodel/redis.rb:163:in `included'
    from /home/nir0/projects/tyuru-dev/app/models/roster.rb:2:in `include'
```

**Comment by nir0** [comment]
sry, i didn't look at juggernaut as at _just_ transport protocol
