### ISSUE TITLE
Error: The "sys" module is now called "util".

### ISSUE THREAD

**Issue by isstaif** [maccman/juggernaut#128]
I'm not sure if this issue is the same as issue #125, so I thought I would open a new one.

I installed juggernaut using npm, here is the installation info:

```
/usr/local/bin/juggernaut -> /usr/local/lib/node_modules/juggernaut/server.js

juggernaut@2.1.1 /usr/local/lib/node_modules/juggernaut
├── node-static-maccman@0.5.3
├── redis@0.6.6
├── optimist@0.2.8 (wordwrap@0.0.2)
└── socket.io@0.8.7 (policyfile@0.0.4, redis@0.6.7, socket.io-client@0.8.7)
```

And when I ran juggernaut I got the following error:

```
 node.js:249
         throw e; // process.nextTick error, or 'error' event on first tick
               ^
 Error: The "sys" module is now called "util".
     at sys.js:1:69
     at NativeModule.compile (node.js:586:5)
     at Function.require (node.js:554:18)
     at Function._load (module.js:297:25)
     at Module.require (module.js:357:17)
     at require (module.js:373:17)
     at Object.<anonymous> (/usr/local/lib/node_modules/juggernaut/node_modules/redis/lib/util.js:5:20)
     at Module._compile (module.js:444:26)
     at Object..js (module.js:462:10)
     at Module.load (module.js:351:32)
```

What is the cause of the problem? I'm using Node v0.7.9-pre.

**Comment by ssh123** [comment]
sys.js:1
throw new Error(
      ^
Error: The "sys" module is now called "util".
    at sys.js:1:69
    at NativeModule.compile (node.js:585:5)
    at Function.require (node.js:553:18)
    at Function._load (module.js:297:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/juggernaut/node_modules/redis/lib/util.js:5:20)
    at Module._compile (module.js:449:26)
    at Object..js (module.js:467:10)
    at Module.load (module.js:356:32)
same question!
