### ISSUE TITLE
Problem with utils

### ISSUE THREAD

**Issue by PanosJee** [maccman/juggernaut#21]
Hello there, 
I am trying to start the node server but I got:
The 'sys' module is now called 'util'. It should have a similar interface.

node.js:50
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
Error: Cannot find module 'utils'
    at resolveModuleFilename (node.js:265:13)
    at loadModule (node.js:231:20)
    at require (node.js:291:14)
    at Object.<anonymous> (/Users/panosjee/Documents/Work/GitPlay/juggernaut/lib/juggernaut/channel.js:2:13)
    at Module._compile (node.js:348:23)
    at Object..js (node.js:356:12)
    at Module.load (node.js:279:25)
    at loadModule (node.js:251:12)
    at require (node.js:291:14)
    at Object.<anonymous> (/Users/panosjee/Documents/Work/GitPlay/juggernaut/lib/juggernaut/publish.js:4:15)

I tried to require("util") instead of utils but then i got a simple exception:
The 'sys' module is now called 'util'. It should have a similar interface.

node.js:50
    throw e; // process.nextTick error, or 'error' event on first tick
    ^
TypeError: Object 

I search for any node-utils package but it seemed it was not what I needed. 
I am using node v0.3.1-pre <- oops it seems it is the unstable version, cheching the stable version atm

**Comment by PanosJee** [comment]
That was my fault, i was running unstable
