### ISSUE TITLE
Socket.io Error while starting the server

### ISSUE THREAD

**Issue by meetme2meat** [maccman/juggernaut#27]
I have already worked with juggernaut(ruby) so just thought of exploring juggernaut on node but it seem that i have to wait for until the error get resolved .I'm new to node so cant figure what the error is 

throw e;
    ^
Error: Cannot find module 'socket.io'
    at loadModule (node.js:275:15)
    at require (node.js:411:14)
    at Object.<anonymous> (/home/virenegi/Desktop/juggernaut/lib/juggernaut/server.js:4:16)
    at Module._compile (node.js:462:23)
    at Module._loadScriptSync (node.js:469:10)
    at Module.loadSync (node.js:338:12)
    at loadModule (node.js:283:14)
    at require (node.js:411:14)
    at Object.<anonymous> (/home/virenegi/Desktop/juggernaut/lib/juggernaut/index.js:4:15)
    at Module._compile (node.js:462:23)

My node version is 0.2.4 and i also followed the step mention in http://sixarm.com/about/node_js_socket_io_fix_for_sys_and_util.html and make resulted in no error.

**Comment by maccman** [comment]
Have you checked out the submodules?

git clone git://github.com/maccman/juggernaut.git --recursive
