### ISSUE TITLE
Error when trying to start Juggernaut

### ISSUE THREAD

**Issue by mvilrokx** [maccman/juggernaut#31]
Hi,

I installed all pre-reqs as per README, redis works fine.  However, when I try to start the server, I get the following error:

> node server.js 
> 3 Dec 00:40:14 - socket.io ready - accepting connections

node.js:66
      throw e; // process.nextTick error, or 'error' event on first tick
      ^
Error: EADDRINUSE, Address already in use
    at Server._doListen (net.js:953:42)
    at net.js:924:14
    at Object.lookup (dns.js:126:5)
    at Server.listen (net.js:918:20)
    at [object Object].listen (/home/mark/ruby/work/juggernaut/juggernaut/lib/juggernaut/server.js:52:21)
    at Object.listen (/home/mark/ruby/work/juggernaut/juggernaut/lib/juggernaut/index.js:9:10)
    at Object.<anonymous> (/home/mark/ruby/work/juggernaut/juggernaut/server.js:2:12)
    at Module._compile (node.js:347:32)
    at Object..js (node.js:355:14)
    at Module.load (node.js:278:27)

I presume that some ports are already being used on my system and this is why I get that error however, I checked and nothing is already serving port 8080 (which I assume juggernaut is using).  I even changed the port in juggernaut.js (  this.port = this.options.port || 8080;), assuming this is where it comes from, to some random port, still get that error (slim chance that a random number is also being listened to).  What other ports do I need to worry about?

Cheers.

**Comment by mvilrokx** [comment]
ok, I actually got it to work by shutting down my Apache server, so something is trying to attach itself to port 80 when I do node server.js, which obviously my Apache server is already occupying.  So how do I run my Apache server (which I need to serve my website) and Juggernaut to run together on my server?

**Comment by mvilrokx** [comment]
I dropped apache all together and went with nginx + passenger, problem solved.  Not sure why, but it'll do
