### ISSUE TITLE
Problem publishing from Ruby

### ISSUE THREAD

**Issue by mvaled** [maccman/juggernaut#37]
I have just cloned the repo, and built and instelled the gem (in the client directory).

I also have successfully compiled node.js (master branch). 

I installed redis-server (Ubuntu package). And installed the gem redis 2.1.1.

However when I try to publish from Ruby (irb) I get this:

```
require 'rubygems'
require 'juggernaut'
Juggernaut.publish('channel1', 'data')


RuntimeError: -ERR unknown command 'publish'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/connection.rb:86:in `format_error_reply'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/connection.rb:76:in `format_reply'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/connection.rb:71:in `read'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/client.rb:83:in `read'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/client.rb:30:in `call'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/client.rb:63:in `process'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/client.rb:154:in `ensure_connected'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/client.rb:58:in `process'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/client.rb:118:in `logging'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/client.rb:57:in `process'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis/client.rb:29:in `call'
from /var/lib/gems/1.8/gems/redis-2.1.1/lib/redis.rb:576:in `publish'
from /var/lib/gems/1.8/gems/juggernaut-2.0.1/lib/juggernaut.rb:17:in `publish'
from (irb):3
```

Any ideas?

Best regards,
Manuel.

**Comment by maccman** [comment]
You using an old version of Redis.

Try doing 'which redis' to make sure it's the right binary you're executing.

**Comment by mvaled** [comment]
Yep. The redis version on the Ubuntu repo is certainly old. I compiled it, and now I can publish with the juggernaut gem.

Thanks.
