### ISSUE TITLE
when i start sudo  node server.js i am getting this error

### ISSUE THREAD

**Issue by felix123** [maccman/juggernaut#47]
2 Mar 19:05:12 - socket.io ready - accepting connections

node.js:116
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: EADDRINUSE, Address already in use
    at Server._doListen (net.js:1062:5)
    at net.js:1033:14
    at Object.lookup (dns.js:132:33)
    at Server.listen (net.js:1027:20)
    at [object Object].listen (/home/openweb/Desktop/juggernaut/lib/juggernaut/server.js:55:21)
    at Object.listen (/home/openweb/Desktop/juggernaut/lib/juggernaut/index.js:9:10)
    at Object.<anonymous> (/home/openweb/Desktop/juggernaut/server.js:2:12)
    at Module._compile (module.js:373:26)
    at Object..js (module.js:379:10)
    at Module.load (module.js:305:31)

I install node-0.4.0
            redis-2.0.3
            juggernaut

**Comment by maccman** [comment]
Sounds like you've got something else running on that port

ps aux | grep 8080

You can change the port with the ENV variable 'port'.

**Comment by felix123** [comment]
Thanks.when i running this ps aux there is no process displaying.which version is working for node ,redis and juggernaut?

**Comment by felix123** [comment]
while i am installing  node-v0.2.5 the following three things are not found

Checking for header port.h               : not found 
Checking for header sys/event.h          : not found
Checking for function kqueue             : not found
