### ISSUE TITLE
require 'node-static' should be changed to 'node-static-maccman'

### ISSUE THREAD

**Issue by Knack** [maccman/juggernaut#54]
I've just done a clean install of node, npm and juggernaut's latest version (2.0.3), and when I run juggernaut I get the following error:

```
node.js:178
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'node-static'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/home/paco/local/node_modules/juggernaut/lib/juggernaut/server.js:7:16)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at require (module.js:348:19)
    at Object.<anonymous> (/home/paco/local/node_modules/juggernaut/lib/juggernaut/index.js:4:15)
```

Changing line 7 in lib/juggernaut/server.js from:

```
var nstatic  = require 'node-static'
```

to

```
var nstatic  = require 'node-static-maccman'
```

solves the problem.

**Comment by Knack** [comment]
Version 2.0.3 is packaged with a custom version of node-static, called "node-static-maccman". 

https://github.com/maccman/juggernaut/commit/49bba93926f3f9a005a923c86d924d3d28732c7b

So, I think that the only change that's missing is the one indicated in my previous comment. It's clearly a bug, that is hidden if you already have installed node-static

**Comment by maccman** [comment]
Ah yes, how embarrassing. All fixed now - update npm. 

Cheers,
Alex
