### ISSUE TITLE
TypeError: Cannot call method 'indexOf' of undefined

### ISSUE THREAD

**Issue by iros** [maccman/juggernaut#91]
When i run sudo node server.js I can interface with the client connection just fine until the user closes the browser and then the node server.js dies with the following message:

/apps/juggernaut/node_modules/socket.io/lib/manager.js:466
      this.rooms[room].splice(this.rooms[room].indexOf(id), 1);
                                               ^
TypeError: Cannot call method 'indexOf' of undefined
    at Manager.onDisconnect (/apps/juggernaut/node_modules/socket.io/lib/manager.js:466:48)
    at Manager.onClientDisconnect (/apps/juggernaut/node_modules/socket.io/lib/manager.js:428:8)
    at WebSocket.end (/apps/juggernaut/node_modules/socket.io/lib/transport.js:467:20)
    at Parser.<anonymous> (/apps/juggernaut/node_modules/socket.io/lib/transports/websocket.js:40:10)
    at Parser.emit (events.js:61:17)
    at Parser.parse (/apps/juggernaut/node_modules/socket.io/lib/transports/websocket.js:317:12)
    at Parser.add (/apps/juggernaut/node_modules/socket.io/lib/transports/websocket.js:303:8)
    at Socket.<anonymous> (/apps/juggernaut/node_modules/socket.io/lib/transports/websocket.js:157:17)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:673:31)

**Comment by iros** [comment]
Solved with the Socket.io upgrade 0.7.9 in this pull request. 
https://github.com/maccman/juggernaut/pull/90
